In [1]:
print("Multimedia Security Experiment 2")

Multimedia Security Experiment 2


In [2]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import myipf
#from mpl_toolkits.mplot3d.axes3d import Axes3D

%matplotlib inline
plt.rcParams["font.sans-serif"] = ["SimHei"] # 用来正常显示中文
plt.rcParams["axes.unicode_minus"] = False # 用来正常显示负号
%config InlineBackend.figure_format = "svg"

## 1.计算单幅图像的基本统计值：均值、方差、标准差；
这里采用内置函数实现

In [3]:
img1 = plt.imread("images/lena.bmp") # 都是三通道图像
img2 = plt.imread("images/panda.bmp")
#plt.imshow(img)
print("均值：", img1.mean())
print("列均值", img1.mean(axis=0))
print("行均值", img1.mean(axis=1)) # 方差，标准差类似
print("方差：", img1.var())
print("标准差", img1.std())

均值： 128.44114933333333
列均值 [[157.962  66.914  81.494]
 [158.424  67.626  81.984]
 [158.552  67.48   82.306]
 ...
 [179.048 112.022 111.026]
 [178.842 111.746 111.024]
 [178.582 111.824 110.736]]
行均值 [[204.918 107.64  101.224]
 [205.024 107.564 101.142]
 [204.68  106.766 100.12 ]
 ...
 [170.56   89.224  99.362]
 [171.226  89.944 100.02 ]
 [171.28   90.026 100.11 ]]
方差： 3464.548752599032
标准差 58.86041753673713


## 2.计算多幅图像之间的相关系数、协方差等；
自己编写函数实现，回顾相关概念

- 协方差，若分母为 N-1 为无偏估计

$$cov(X, Y) = \frac{\sum_\nolimits{i=1}^n(X_i - \bar X)(Y_i - \bar Y)}{N} $$

- 相关系数

$$R = \frac{cov(X_i, Y_i)}{\sqrt{var(X_i)var(Y_i)}} $$

In [4]:
img1 = img1.mean(axis=2) # 转为单通道图像
img1.shape

(500, 500)

In [5]:
img2 = img2.mean(axis=2) # 转为单通道图像
img2.shape

(500, 500)

In [6]:
print("协方差: ", myipf.covariance(img1, img2))
#print(corrcoef(img1, img2))
print("\n\n\n相关系数: ", myipf.corr(img1, img2))

协方差:  [[-187.70867556 -181.07625333 -177.62966667 ... -670.16974667
  -678.84879333 -681.04754444]
 [-173.12767289 -165.25318844 -160.84108889 ... -632.06810044
  -639.63063867 -644.15079778]
 [-149.14286578 -141.83058578 -137.36251111 ... -577.00310311
  -583.01627067 -583.75814   ]
 ...
 [ 263.01945956  252.37344178  238.13875556 ... -931.34370844
  -910.51734578 -896.68088   ]
 [ 256.25233244  245.39305244  231.04906667 ... -948.15647467
  -925.25460711 -910.23613778]
 [ 247.36816356  235.67201689  220.78006667 ... -979.90677244
  -956.250236   -940.52026   ]]



相关系数:  [[-0.16322088 -0.15734178 -0.15472722 ... -0.27113015 -0.2755666
  -0.27848818]
 [-0.15398386 -0.14687563 -0.14330639 ... -0.26156173 -0.26558291
  -0.26942273]
 [-0.13549352 -0.12875886 -0.12500981 ... -0.24389102 -0.24726285
  -0.24939455]
 ...
 [ 0.16087137  0.1542502   0.14590857 ... -0.26503455 -0.25998079
  -0.25790916]
 [ 0.15627687  0.1495479   0.14115327 ... -0.26903483 -0.26342093
  -0.26104713]
 [ 0.149666

## 3.计算两幅图像之间的差异（均方差 MSE）以及峰值信噪比（PSNR）。

- 均方差

$$ MSE=\frac{1}{mn} \sum_{i=1}^m\sum_{j=1}^n \left\| X_{ij} - Y_{ij} \right\|^2 $$

- 峰值信噪比

$$ PSNR= 10 \cdot \log_{10}\left(\frac{MAX_X^2}{MSE}\right) $$

> PSNR经常应用于测量图片的重建质量，也可作为衡量图像失真或是噪声水平的客观标准。2个图像之间PSNR值越大，则越相似。

In [7]:
M = img1 - img2
MSE = np.sum(M.flatten() * M.flatten()) / np.size(img1)
#SNR = 10 * np.log10(np.sum(img1.flatten() * img1.flatten()) / MSE / np.size(img2))
PSNR = 10 * np.log10((255 ** 2) / MSE)
print("均方差：", MSE)
print("峰值信噪比：", PSNR)

均方差： 8276.997983555555
峰值信噪比： 8.952075114719865
